server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HelloWorldwangjiacheng/springcloud-config.git
        #### 搜索目录
          search-paths:
            - springcloud-config
        #### 读取分支
        label: master

eureka:
  instance:
    instance-id: config-center3344
    # 访问路径可以显示IP地址
    prefer-ip-address: true
    # Eureka客户端向服务端发送心跳的时间间隔,单位为秒(默认是30秒)
    lease-renewal-interval-in-seconds: 10
    # Eureka服务端在收到最后一次心跳后等待时间上限,单位为秒(默认是90秒),超时删除服务
    lease-expiration-duration-in-seconds: 30
  client:
    # 表示是否将自己注册进EurekaServer,默认是true
    register-with-eureka: true
    # 是否从EurekaServer中抓取已有的注册信息,默认是true.
    # 单节点无所谓,集群必须设置成true,这样才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址,集群配置
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      # 单机版
        defaultZone: http://eureka7001.com:7001/eureka/
